### ISSUE TITLE
请问baud rate是否能提高

### ISSUE THREAD

**Issue by yangzj208** [Seeed-Studio/seeed-ambd-firmware#15]
**Is your feature request related to a problem? Please describe.**
之前版本的baud rate为1843200，为什么变成了614400

**Describe the solution you'd like**
能否发布一个1843200的版本

**Describe alternatives you've considered**
目前应用的场合传输量稍大，一次传输时间过长

**Additional context**

**Comment by Pillar1989** [comment]
@yangzj208  主要还是因为两个MCU的处理速度更不上，太高的底层传输影响稳定性，而且在应用端测试的真实的网络速度并不高。

**Comment by yangzj208** [comment]
@Pillar1989 感谢回复。
目前我测试大概一次传600k，直接rtl8720这边传是大概3秒钟，时间可接受。
但是通过samd51这边传过去得好几十秒了，调整了下延时参数，现在在11秒上不去了，现在瓶颈在波特率了，所以想看看提高的效果

**Comment by yangzj208** [comment]
@Pillar1989 我尝试自己用windows去执行arduino-build.ps1进行编译，没能成功。报很多类似这样的错误：
D:\ChyST\projects\wio\third\seeed-ambd-firmware\src\wifi\wifi_api.c:1973:19: error: 'struct tcp_pcb' has no member named 'errf_external'
             tpcb_p->errf_external = rpc_tcp_err_external;
                   ^~
D:\ChyST\projects\wio\third\seeed-ambd-firmware\src\wifi\wifi_api.c:1975:64: error: invalid application of 'sizeof' to incomplete type 'struct rpc_tcp_pcb'
             rtpcb_p = (struct rpc_tcp_pcb *)erpc_malloc(sizeof(struct rpc_tcp_pcb));
                                                                ^~~~~~
D:\ChyST\projects\wio\third\seeed-ambd-firmware\src\wifi\wifi_api.c:1976:35: warning: passing argument 2 of 'copy_tp_to_rtp' from incompatible pointer type [-Wincompatible-pointer-types]
             copy_tp_to_rtp(tpcb_p,rtpcb_p);
                                   ^~~~~~~
D:\ChyST\projects\wio\third\seeed-ambd-firmware\src\wifi\wifi_api.c:51:6: note: expected 'struct rpc_tcp_pcb *' but argument is of type 'struct rpc_tcp_pcb *'
 void copy_tp_to_rtp(struct tcp_pcb *pcb,struct rpc_tcp_pcb *rpc_pcb)
      ^~~~~~~~~~~~~~
D:\ChyST\projects\wio\third\seeed-ambd-firmware\src\wifi\wifi_api.c:1977:27: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
             pcb_out->data = rtpcb_p;
                           ^
D:\ChyST\projects\wio\third\seeed-ambd-firmware\src\wifi\wifi_api.c:1978:42: error: invalid application of 'sizeof' to incomplete type 'struct rpc_tcp_pcb'
             pcb_out->dataLength = sizeof(struct rpc_tcp_pcb);
                                          ^~~~~~
D:\ChyST\projects\wio\third\seeed-ambd-firmware\src\wifi\wifi_api.c:1955:13: warning: unused variable 'ret' [-Wunused-variable]
     int32_t ret = ERR_ARG;
             ^~~
D:\ChyST\projects\wio\third\seeed-ambd-firmware\src\wifi\wifi_api.c: In function 'rpc_tcp_arg':
D:\ChyST\projects\wio\third\seeed-ambd-firmware\src\wifi\wifi_api.c:1997:19: error: dereferencing pointer to incomplete type 'struct rpc_tcp_pcb'

**Comment by LynnL4** [comment]
Hi
我更新了编译的脚本，https://github.com/Seeed-Studio/seeed-ambd-firmware/commit/d2264c0d7ca6c4dd61ce729eab1d4dd45e7f1e92 你可以根据你自己的需求更改波特率。
https://github.com/Seeed-Studio/seeed-ambd-firmware/blob/d2264c0d7ca6c4dd61ce729eab1d4dd45e7f1e92/src/erpc_setup.cpp#L42
除了更改固件的波特率， 你还需要更改Seeed_Arduino_rpcUnified的波特率

https://github.com/Seeed-Studio/seeed-ambd-firmware/blob/d2264c0d7ca6c4dd61ce729eab1d4dd45e7f1e92/src/erpc_setup.cpp#L42

**实测不要成功1843200， 并且如果更改了波特率，不能保证通讯的效果**
