### ISSUE TITLE
WiFi.scanNetworks() Randomly hangs forever.

### ISSUE THREAD

**Issue by oernohazy** [Seeed-Studio/seeed-ambd-firmware#18]
**Describe the bug**
Calling  WiFi.scanNetworks(/*async*/true, /*hidden*/true, /*passive*/false,  300); will periodically hang, and never return.
Using Version 2.1.3
I'm using WioTerminal

**To Reproduce**
Compile and load the WiFiScan example.

But I observe the following randomly hangs:

    **_Serial.println("scan start");

    // WiFi.scanNetworks will return the number of networks found
    int n = WiFi.scanNetworks();   
    Serial.println("scan done");_**

Also Async mode hangs too. 

**Expected behavior**

I would expect this function to always return especially in the Async mode.

**Desktop (please complete the following information):**
 - OS: [OSX 11.3.1]
 - Browser [safari]
 - Version [14.1]

**Additional context**
I tried to scan with different intervals, but the demo uses 5 second delay between scans, and that will hang randomly from between 2 min to sometimes running up to 10 min before hanging.

**Comment by oernohazy** [comment]
I noticed, after adding the SAMCrashMonitor, the issue seems to be much better.  Ie the watchdog hardly ever reboots the device, and yet the scan doesn't hang. I thought it was a coincidence, so I reverted to code before adding the watchdog, and it hangs within a few min.

**Comment by lozaning** [comment]
Scan networks returns -2 and -1 for me regularly, which then causes my program ot hang, and the wifi chip never recovers. Adding a watchdog did not fix the issue for me.

**Comment by oernohazy** [comment]
I still see my Wik reboot all the time due to the Scan hanging.  For me the watchdog did the trick to at least reboot. 
Seems like Seed doesnt want to fix the root of the problem .

**Comment by lozaning** [comment]
What watchdog are you using? I found and implemented this one based on what you said: (https://github.com/cyrusbuilt/SAMCrashMonitor)

But generally when things hang all I see is

`Starting Scan
Scan Done
Network status -2
The wifi is fucked
=========================================

Reset reason: 32, Reset requested by Watchdog
=========================================`

**Comment by oernohazy** [comment]
I am using That crash monitor.  The difference is I never get the ScanDone.  Mine would just hang in the scan and the watchdog reboots the Wio. 

in the void setup () I added these lines

  SAMCrashMonitor::begin();
  SAMCrashMonitor::disableWatchdog(); // Make sure it is turned off during init.
  SAMCrashMonitor::dump();

  SAMCrashMonitor::enableWatchdog(WD_INTERVAL_MS);

and then anywhere I wait for keypress or main loop I have  SAMCrashMonitor::iAmAlive();
