### ISSUE TITLE
Since firmware version 2.0.2 NTP Client not working

### ISSUE THREAD

**Issue by RoSchmi** [Seeed-Studio/seeed-ambd-firmware#3]
In my application on the Wio Terminal
https://github.com/RoSchmi/AzureDataSender_Wio_Terminal
(commit of Nov. 19. 2020, which is working with firmware v2.0.1)
I used a ntp client 
https://github.com/sstaub/NTP
with firmware version 2.0.1 and rpcWiFi library.
As far as I could see (without intensive testing) everything worked flawlessly.
After updating the firmware to v2.0.2 and the other libraries to the latest versions as of 18.11.2020 the ntp client doesn't work. (doesn't return from 'ntp.begin()';

**Comment by ansonhe97** [comment]
Hi I'm just running the examples from the NTP library and got this:

![image](https://user-images.githubusercontent.com/47582872/99607109-126ad280-2a46-11eb-92eb-2cbe37684b0a.png)

So this is not working in your case?

**Comment by ansonhe97** [comment]
Think i found out about the bug, can i ask what wifi bandwidth are you using in your example (2.4 or 5G)

**Comment by RoSchmi** [comment]
Hi, I'm just trying to set up my App with the latest libraries to test ntp again.
But at the moment it doesn't compile On PlatformIO because of a missing reference.
Can you please give me an advice?


![sfud h dependecy](https://user-images.githubusercontent.com/24595510/99651608-20751f00-2a57-11eb-9415-88f7ef7322c3.png)

I think that I use 2,4 GHz band but would have to make more investigations to say for sure.
However I don't think that this is the reason. I did some preliminary tests with this ntp client
https://forum.seeedstudio.com/t/stable-wifi-ntp-failing/254153
When I use my hosted WiFi network on my PC I can see with wireshark that the DNS request is going out but then Wio Terminal doesn't use the responded
Ip-Address.

One more question: Should we better discuss such matters on the community forum or by opening an issue on GitHub?

**Comment by RoSchmi** [comment]
Okay, I found the missing reference to sfud.h. It's correctly decribed in the WiKi, but for lazy guys like me, who think that they do not need to read everything in detail, it would perhaps be better to mention on the first page, that besides
Seeed_Arduino_FS additionally Seeed_Arduino_SFUD has to be included.

Then I had this other compiler message concerning the 'wifi_clear_reconnect_data' command. Preliminary I commented out this command in WiFiSTA.cpp

![WiFi_clear_reconnect](https://user-images.githubusercontent.com/24595510/99663866-92edfb00-2a67-11eb-832b-f7a4495b032b.png)

Perhaps for Seeed_Arduino_mbedtls it should be mentioned that actually the dev branch should be used.

After this changes it compiled.
On wireshark I can see that the DNS request for the ntp server is executed but the Ip address delivered is not used (no request to the ntp server).
What could I be doing wrong?

**Comment by RoSchmi** [comment]
To confirm the issue I reflashed firmware v2.0.1 to the Wio Terminal   ---> ntp client works
then: I download and reflash firmware v2.02 again: ---> ntp client doesn't work

**Comment by RoSchmi** [comment]
I did some more investigations:

1) I set up a ntp client according to the example in the Seeed Wiki.
Worked with firmware v2.0.1, worked **not** with firmware v2.0.2

2) I changed the the SSID names of my dual band router Fritz!Box 6490 (Fritz!Box is very popular in Germany) to different names for 2.4 and 5 GHz. 
I could get WiFi connection to both of them but ntp didn't work with firmware v2.0.2.

3) I changed the dns server of my router (standard is dns through the internet provider) to dns server of google for Ipv4 and Ipv6.
I think that only one time after this change ntp worked for the Wio Terminal with firmware v2.0.2. 
However after switching the dns server of the router back to the standard setting I couldn't reproduce to have it working with google dns and firmware v2.0.2. (I do not understand how this could be).

I would suspect that something affecting dns has changed from firmware v2.0.1 to v2.0.2 which seems to be the cause of this issue.

**Comment by RoSchmi** [comment]
I think I'm getting nearer to the reason.

Using wireshark I could see that the ntp request and the response are ok.

Going into the code I could see in the debugger that in WiFiUdp.cpp the variable len returned with a wrong result.
It should return with content 48 but in firmware v2.0.2 it returned with something like 2063598096. Then the program crashed when filling the rx_buffer.
Can it be that there is a timing problem between writing and receiving from the socket?

![Wrong return for len](https://user-images.githubusercontent.com/24595510/99882603-09365d00-2c22-11eb-9bdb-0974119e1621.png)

**Comment by lyzsuper** [comment]
OK,we will check this problem,it will take some time

**Comment by lyzsuper** [comment]
Hi,RoSchmi 

I check my reuslt,and it could run successfully as below

![result](https://user-images.githubusercontent.com/20987550/100039085-85f25280-2e3f-11eb-82d9-b90e10c254d3.png)

![code](https://user-images.githubusercontent.com/20987550/100039110-8ee32400-2e3f-11eb-8541-57e5a1c994bf.png)
 
PS:
Could you check your rpcUnified & rpcWiFi libraries was latest version?
https://github.com/Seeed-Studio/Seeed_Arduino_rpcUnified
https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi

**Comment by RoSchmi** [comment]
Thanks a lot. You are right, it works now for me as well.
I didn't notice that I accidently had set the link to the rpcUnified library in PlatformIO.ini to a fork of this repo which I made some time ago. 
So I was falsely thinking to have the latest version of rpcUnified, which was not the case.
I'm sorry for wasting your time. I have closed the issue.
