### ISSUE TITLE
Make `rpc_wifi_scan_get_ap_records` take an offset

### ISSUE THREAD

**Issue by twitchyliquid64** [Seeed-Studio/seeed-ambd-firmware#4]
https://github.com/Seeed-Studio/seeed-ambd-firmware/blob/98623fbc6d9b1f07fde28cfd82ec8cd23b5b4040/erpc_idl/rpc_wifi_conf.erpc#L69

The problem with this is that all implementations need to have a receive buffer thats the size of `WL_NETWORKS_LIST_MAXNUM * sizeof(rtw_scan_result_t)` (nearly 4k of RAM!). Theres no need for this, if you provide a way to get a subset of the network across multiple RPCs.

It would be nice if I could give an offset to `rpc_wifi_scan_get_ap_records` to get `number` entries starting at a particular position `offset`.

For example, maybe implement it like this?

eRPC:

```
 rpc_wifi_scan_get_ap_records_with_offset(uint16 number, uint16 offset, out binary _scanResult) -> int32 
```

Implementation:

```cpp
int32_t rpc_wifi_scan_get_ap_records_with_offset(uint16_t number, uint16_t offset, rtw_scan_result_t *_scanResult)
{
  if ((number+offset) > WL_NETWORKS_LIST_MAXNUM || _scanResult == NULL)
  {
    return RTW_ERROR;
  }

  memcpy(_scanResult, _scan_networks[offset], sizeof(rtw_scan_result_t) * number);
  return RTW_SUCCESS;
}
```

What do you think?

Thanks!
Tom

**Comment by LynnL4** [comment]
Yes, this optimization is already in our schedule! Thank you.

**Comment by Pillar1989** [comment]
We think that's the best way to solve this issue.
https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi/commit/e5dbe5ec3927a00b7a477dbce3ea06ddbe56d004

**Comment by twitchyliquid64** [comment]
I don't think that commit solves the issue - theres no way to read a scanned network at some offset.

Without an offset-compatible API, chips with limited RAM constraints will not be able to talk eRPC to enumerate the full list of access points.
